- hosts: webServer
  become: true
  tasks:
    - name: Project copy from server 1 to server 2
      ansible.builtin.copy:
        src: "/var/jenkins_home/workspace/spring-projects/target/spring-petclinic-3.0.0-SNAPSHOT.jar"
        dest: "/tmp/spring-petclinic-3.0.0-SNAPSHOT.jar"
    - name: Start petclinic application
      command: "java -jar /tmp/spring-petclinic-3.0.0-SNAPSHOT.jar"
